### ISSUE TITLE
Takes too long

### ISSUE THREAD

**Issue by jeremys18** [jeremys18/BeatSaber-All_Songs_Downloader#1]
Because of rate limits, this takes a long time to get the song info. Nothing the app can do about limits but refactor so that it calls my own service on a server to get the json of all songs.

Have server do all the long work of getting latest info once every 24 hours. 

Allow this app to simply make a call to my server to get latest list of all song info. Saving this app hours and speeding it up drastically.

**Comment by Whimb** [comment]
It also just vanishes after a period of time, upon clicking either Check or Download.
No error, nothing.

Is forever too long? ¯\\_(ツ)\_/¯

**Comment by jeremys18** [comment]
Code complete. Just need to host on server and set URL...
